name: Auto PR

on:
  push:
    branches:
      - "**"  # Support wildcard matching

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: diff
        run: |
          echo "No difference with main — adding empty commit..."
          git commit --allow-empty -m "init"
          git push origin HEAD
      - name: pull-request
        uses: diillson/auto-pull-request@v1.0.1
        with:
          source_branch: ""                                 # If blank, default: triggered branch
          destination_branch: "main"                      # If blank, default: master
          pr_title: "Pulling ${{ github.ref }} into master" # Title of pull request
          pr_body: |                                        # Full markdown support, requires pr_title to be set
            :crown: *An automated PR*
          pr_label: "auto-pr"                               # Comma-separated list (no spaces)
          pr_draft: true                                    # Creates pull request as draft
          pr_allow_empty: true                              # Creates pull request even if there are no changes