name: Auto PR on branch creation

on:
  create:
    branches:
      - '**'

jobs:
  create_pr:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Create Pull Request
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          BRANCH_NAME="${GITHUB_REF##*/}"
          BASE_BRANCH="main"
          
          git checkout -b $BRANCH_NAME
          git commit --allow-empty -m "init branch"
          git push origin $BRANCH_NAME
          
          # Crée la PR même si aucune différence n'existe
          gh pr create \
            --base "$BASE_BRANCH" \
            --head "$BRANCH_NAME" \
            --title "Auto PR: $BRANCH_NAME" \
            --body "Cette PR a été automatiquement créée à partir de la branche $BRANCH_NAME." \
            || echo "PR already exists or no changes detected."
