name: Auto Pull Request - created at branch creation

on:
  push:
    branches-ignore:
      - main
      - master

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Create PR via GitHub API
        run: |
          gh pr create --base main --head ${{ github.ref_name }} \
            --title "PR: ${{ github.ref_name }}" \
            --body "PR automatique créée, même sans différence."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

