name: Auto PR from branch

on:
  push:
    branches-ignore:
      - main
      - master

jobs:
  auto-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create or update pull request
        uses: devops-infra/action-pull-request@v0.6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_branch: ${{ github.ref_name }}
          target_branch: main
          title: "PR: ${{ github.ref_name }}"
          body: |
            auto PR for branch **${{ github.ref_name }}**.
          label: automatic
          allow_no_diff: true

      - name: Link to issue if branch name contains issue number
        if: startsWith(github.ref_name, 'issue/') || contains(github.ref_name, 'fix/')
        run: |
          issue_number=$(echo "${GITHUB_REF_NAME}" | grep -oE '[0-9]+')
          gh pr edit --add-linked-issue $issue_number
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
