name: Auto PR from branch

on:
  push:
    branches-ignore:
      - main
      - master

jobs:
  auto-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: Export short branch name
        run: echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
        env:
          GITHUB_REF: ${{ github.ref }}

      - name: Fetch main branch
        run: |
          git fetch origin main:main

      - name: Create Pull Request
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
          GITHUB_REPO: ${{ github.repository }}
          GITHUB_REF: ${{ github.ref }}
        run: |
          gh pr create \
          --repo=${GITHUB_REPO} \
          --head=staging \
          --base=main \
          --title="Pulling ${GITHUB_REF} into main" \
          --body=":crown: *An automated PR*" \
          --draft  
